### ISSUE TITLE
Error in util.py

### ISSUE THREAD

**Issue by zoeyuchao** [thuml/HashGAN#1]
Hi, thanks for sharing your code. It is a great job. But I meet some errors when I try this script.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-526ca9fb662e> in <module>()
    422 
    423             mAP_ = util.MAPs(MAP_R)
--> 424             mAP_val = mAP_.get_mAPs_by_feature(db, test)
    425             lib.plot.plot("mAP_feature", mAP_val)
    426 

/home/zoe/deeplearning/HashGAN/util.pyc in get_mAPs_by_feature(self, database, query)
    135             rel = np.sum(imatch)
    136             Lx = np.cumsum(imatch)
--> 137             Px = Lx.astype(float) / np.arange(1, self.R + 1, 1)
    138             if rel != 0:
    139                 APx.append(np.sum(Px * imatch) / rel)

ValueError: operands could not be broadcast together with shapes (53952,) (54000,) 

So what should I do to get this net worked？Thanks！

**Comment by bl0** [comment]
Solved!
