### ISSUE TITLE
download the pretrained Generator 

### ISSUE THREAD

**Issue by ximi2018** [thuml/HashGAN#4]
You can download the pretrained Generator models in the release page and modify config file to use the pretrained models.

Hi ,I don't understand how to do this step.

cifar10_G_99999.ckpt.zip
Source code
(zip) 

Source code
(tar.gz) 
which one?

**Comment by bl0** [comment]
cifar10_G_99999.ckpt.zip

**Comment by ximi2018** [comment]
Hello, may I ask if the directory structure of G ﹣ preset ﹣ model ﹣ path: is ". / preset ﹣ models / cifar10 / g ﹣ 99999. CKPT /" g ﹣ 9999.ckpt/cifar/g ﹣ 99999.ckpt.meta, G ﹣ 999.ckpt.index, G ﹣ 9999.ckpt.data-00000-of-00001  
I will prompt the error: original stack trace for 'save / restorev2'

**Comment by bl0** [comment]
I think this should be caused by the TensorFlow version mismatch. 
Maybe you need to try the version I listed in `environment.yml`.
