### ISSUE TITLE
About the input data

### ISSUE THREAD

**Issue by Dokumushikun** [thuml/HashGAN#5]
Hi, i have a problem about finding the input v.In the code it seems that there isnt the input s.and 
 i have not found the loss about the v and s.

**Comment by bl0** [comment]
Actually, the code in this repo simply uses the pre-computed v from s.

**Comment by ximi2018** [comment]
My problem may have nothing to do with the code. I want to ask you how the existing algorithm can solve the problem if the feature map obtained has a 0-1 limit in deep learning. All I know is to replace sign with tanh, but I want to know more,

**Comment by bl0** [comment]
Actually, any math function whose input scope is [-infinity, +infinity] and output scope is [0, 1] is ok for your purpose.
